export const BOARD_SPACES = [
    { index: 0, name: "Salida" },
    { index: 1, name: "Avenida Mediterráneo" },
    { index: 2, name: "Arca Comunal" },
    { index: 3, name: "Avenida Báltica" },
    { index: 4, name: "Impuesto sobre Ingresos" },
    { index: 5, name: "Ferrocarril Reading" },
    { index: 6, name: "Avenida Oriental" },
    { index: 7, name: "Fortuna" },
    { index: 8, name: "Avenida Vermont" },
    { index: 9, name: "Avenida Connecticut" },
    { index: 10, name: "En la Cárcel / De Visita" },
    { index: 11, name: "Plaza San Carlos" },
    { index: 12, name: "Compañía de Electricidad" },
    { index: 13, name: "Avenida Estados" },
    { index: 14, name: "Avenida Virginia" },
    { index: 15, name: "Ferrocarril Pennsylvania" },
    { index: 16, name: "Plaza St. James" },
    { index: 17, name: "Arca Comunal" },
    { index: 18, name: "Avenida Tennessee" },
    { index: 19, name: "Avenida Nueva York" },
    { index: 20, name: "Parada Libre" },
    { index: 21, name: "Avenida Kentucky" },
    { index: 22, name: "Fortuna" },
    { index: 23, name: "Avenida Indiana" },
    { index: 24, name: "Avenida Illinois" },
    { index: 25, name: "Ferrocarril B. & O." },
    { index: 26, name: "Avenida Atlántico" },
    { index: 27, name: "Avenida Ventnor" },
    { index: 28, name: "Compañía de Agua" },
    { index: 29, name: "Jardines Marvin" },
    { index: 30, name: "Váyase a la Cárcel" },
    { index: 31, name: "Avenida Pacífico" },
    { index: 32, name: "Avenida Carolina del Norte" },
    { index: 33, name: "Arca Comunal" },
    { index: 34, name: "Avenida Pennsylvania" },
    { index: 35, name: "Ferrocarril Vía Rápida" },
    { index: 36, name: "Fortuna" },
    { index: 37, name: "Plaza Park" },
    { index: 38, name: "Impuesto de Lujo" },
    { index: 39, name: "El Muelle" },
];

export const getSpaceName = (index: number) => {
    return BOARD_SPACES[index % 40]?.name || `Square ${index}`;
};
